[package]
name = "api_on_crates_io"
version = "0.1.0"
edition = "2021"
description = "just testing how cargo registry works"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
